### ISSUE TITLE
Submit button not expanding

### ISSUE THREAD

**Issue by mpok3** [frogamic/zendesk-submit-expander#3]
Issue with button today (seemed fine yesterday). It is showing the Submit button as blue and behaving as though the expander extension is not there.

Uninstalled and reinstalled to no avail.

Chrome version 68.0.3440.84
Let me know if there's any more details you need.

![screen shot 2018-08-07 at 09 33 17](https://user-images.githubusercontent.com/13885781/43764290-fdda1884-9a24-11e8-9feb-27188fb922b7.png)

**Comment by kenstephens8274** [comment]
Same issue this morning

Chrome Version 67.0.3396.99 (Official Build) (64-bit)

Perhaps an overnight ZD update caused this?

**Comment by alanhogan** [comment]
Hi — I’m an engineer at Zendesk and I can confirm that extensions like this would be expected to break due to a very recent update we rolled out. The submit button (including the menu containing other statuses) was replaced with a new (but functionally identical) version with newer technological underpinnings that are intended to give Zendesk Support a more consistent and accessible interface overall. (Not that I want to give the impression that we think we supercharged the button or anything — this is just part of a wider collection of interface updates.)

Notably, the status colors themselves will be changing as well, shortly.

**Comment by frogamic** [comment]
Hi all, there have been some significant changes in the Zendesk UI but I'm working on fixing this as soon as possible.

**Comment by frogamic** [comment]
I have had a chance to dig into this, unfortunately the old pure CSS solution of styling the menu of submit options as buttons and re-arranging them into a button group won't work with the Zendesk Garden UI. I'm currently investigating using Javascript to create my own Zendesk Garden button group and linking up the onclick events.
The difficulties are:
- Knowing which buttons to display (on-hold and new aren't always enabled)
- The pop up menu doesn't exist until the expander button is clicked, thus can't just call their onClick handlers
- The submit button loads after the document onReady event and again when the ticket div is closed and re-opened, need to somehow detect these events and replace the buttons again.

**Comment by frogamic** [comment]
Just a quick update on this, I have managed to find time today to take a good look at this and how to recreate the extension in Javascript using the Zendesk Garden UI pattern.

Here's a screenshot of the progress so far:

![Zendesk-UI screenshot](https://i.imgur.com/vxL6o1c.png)

The buttons are non-functioning and don't pick up the available and current statuses of the ticket yet and they don't reliably replace the standard drop-up for every ticket opened, so it's still a work in progress at this point.

**Comment by frogamic** [comment]
Another Update:
After learning a lot about Native JS Web APIs, I have added full functionality to the buttons, I have just been having some issues with reliability of injecting the buttons into the page. I haven't given up yet, and am currently testing the 10th beta based on the `dev-garden` branch. Hopefully with the injection redundancy I've built in this should be ready to go live soon.

**Comment by chaoscreater** [comment]
I have faith in you!

**Comment by frogamic** [comment]
The new version is now published!
