### ISSUE TITLE
Menu not showing since yesterday

### ISSUE THREAD

**Issue by alexislg2** [frogamic/zendesk-submit-expander#5]
Hello,
I guess Zendesk made a new modification of their frontend very recently. This time the menu does not show at all with this extension.
I have pulled the latest version (https://github.com/frogamic/zendesk-submit-expander/commit/5c029facff082e95129ce5b78b973f578533eebd) which also fixed a Zendesk frontend modification but problem remains
Any one has the same issue?

From what I saw, the `menu` variable is `null`. I still haven't figured out why.

**Comment by becca-stevens** [comment]
I first noticed this on Friday, another team member is having the same problem. We disabled the extension and can see ZD's normal menu options

**Comment by mattwhosthat** [comment]
I'm also having this problem for about a week now where the entire submit menu is gone.

**Comment by alexislg2** [comment]
Nobody was able to fix this problem?
I'm sorry I am really no CSS expert, I cannot help here

**Comment by frogamic** [comment]
This has been fixed in the latest release (v2.3) which is currently undergoing Chrome Webstore review. This could take up to 30 days to process.
