### ISSUE TITLE
Submit options no longer expand

### ISSUE THREAD

**Issue by CharlesMagnuson** [frogamic/zendesk-submit-expander#8]
It appears that Zendesk released an update this week which broke this Chrome extension. Specifically, the update to the Macros menu appears to have clobbered the functionality of this extension. When I open a ticket, the submit options are no longer expanded.

**Comment by frogamic** [comment]
Hey Charles, thanks for flagging this. I'm looking into a fix soon.

**Comment by nvirsunen** [comment]
This also affects on the "Next ticket in view" function. If this Submit expander extension is ON the "Next ticket.." function does not stay on. If I disable the the whole expander extension then the choise is removed totally from the menu.
![image](https://user-images.githubusercontent.com/69582727/90008812-9bcf7380-dca5-11ea-81a8-a00c68094cbc.png)

**Comment by wyvernvenners** [comment]
Hi Dominic Seems Zendesk have changed a class name - I have played with the source code and managed to get it working on my my machine by changing all references to the class .ticket-resolution-footer to .LRb.LRc

**Comment by CrazyFactoryJan** [comment]
Is it working again? We are planning to use Zendesk and really like to have this feature. 
Can it also be used for other languages beside Englisch? Thank you.

**Comment by frogamic** [comment]
This has been fixed in the latest release (v2.3) which is currently undergoing Chrome Webstore review. This could take up to 30 days to process.
